//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrakSYSSynchronization
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TrakSYSSynchronization.Models;

    public partial class EDBEntities : DbContext
    {
        public EDBEntities(string connectionString)
            : base(connectionString)
        {
        }
   
        public virtual DbSet<tAuditDetail> tAuditDetails { get; set; }
        public virtual DbSet<tAuditHeader> tAuditHeaders { get; set; }
        public virtual DbSet<tScript> tScripts { get; set; }
        public virtual DbSet<tScriptGroup> tScriptGroups { get; set; }
    }
}
