//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrakSYSSynchronization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAuditHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tAuditHeader()
        {
            this.tAuditDetails = new HashSet<tAuditDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTimeOffset AuditDateTime { get; set; }
        public string User01 { get; set; }
        public string User01FullName { get; set; }
        public string User02 { get; set; }
        public string User02FullName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> EntityID { get; set; }
        public string EntityName { get; set; }
        public string EntityTypeName { get; set; }
        public string Reason { get; set; }
        public bool IsDatabaseTransfer { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UploadedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAuditDetail> tAuditDetails { get; set; }
    }
}
