//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrakSYSSynchronization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tScriptGroup
    {
        public int ID { get; set; }
        public string Guid { get; set; }
        public string Name { get; set; }
        public string AltName { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SiteID { get; set; }
        public int Type { get; set; }
        public string Key { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsReadOnly { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UploadedDateTime { get; set; }
        public string TemplateData { get; set; }
    }
}
